#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
Open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAIdSURBVDiNjZO/S5dRFMY/532vb0mgawTh0lLQGKhLP6QlDXJq0KXFwaDmhv6ChhA3h4oG"
    "+w8EI4UITStoaIoQIbVFQi3N7/fec89p+OqblmDPcO65l3uf5znn3itDQ0McRMrNhoiU7i4i"
    "AkBRFCIitLW1ff613bhcVdX6/v7Q1dX11N1v7i8sLX858ezJc4qiQETYJxERJl9Mnp+envqA"
    "cxH4ARDMbHBwcLDTzMg5Mzb+mJWVFZrNJgDuTs4ZM2N4aJitzc2zC+8X5uNuulRV1W5IKbmq"
    "sr6+jqruW2bx3eKh0nq6uwEYHb0r5US4MDf/ZgxjZI8goaqYGSJCVVX0XevD3WsXZVnWIr09"
    "vfJ2Ye62GSNBVU01k3OuHYQQmJl9Rc65dnD1yjVijK2JgJkVUBBSSh5jrAn2uk3/jYFa/e+x"
    "/WQ7OAYQYoymqkzMOw0N0HmLgYcvcWuJ+YHYIthL2vs7yqJYDapKSomdCI/uX+coSB3+IKrx"
    "YHzmTEgpWUoJcEqBj8tbR5IcRFkK506fAnEPKSVTTQhQiFCF4liCbI4bCGJ715gRCcRklHKw"
    "4sPQ7DSToWY0UwbwoKoWY0Qk8G2jwc+GotlJ2TFzzJ1sTtJWDhBKYfX7LohYEBEzMwTY2I5s"
    "N5Sk/3oIpdSdLArY3ImIuwd3Z22j9WBef1qtP89x2NnZBZGvIRfts1NLHXfAWV5a+6/DtLxs"
    "ZOTeb/gCSx11MtnDAAAAAElFTkSuQmCC")
getOpenData = Open.GetData
getOpenImage = Open.GetImage
getOpenBitmap = Open.GetBitmap

#----------------------------------------------------------------------
Exit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKcSURBVDiNdZNPaBRJFMZ/r6q6u3qyg3uIHowg6s5hL+JFQYUQ0atoUMOq5CgeDCwaD5K7"
    "Lh724B+MoFdFUC+eRFAUJGoEhRUc3R13QiZsQGeiyfRkOp3uqT3EGf8/+Kh6l69+Xz2eHBzc"
    "fzJJkhF+UCKC7/vYwGKMARGyLMUG9s+zZ86fMEmSjPTv2kO5XCaKIhqNBs1mkziOSdOUCxfO"
    "o5RCa4NSCoBm3OTsuTPDwGkDEAQBQRCQJAlpmtJqtXDOobUGQCmNMeZjL2ht6FnZA5BXAPl8"
    "njAMyeVyhGHYuVtrAUEERBSl0Ys82L4dEcHaEMCYdk5rLc65Tm4RQSmFCLgs49nRIbJqlQ/F"
    "IvW/X8N/0/wzOtptlhAVWmu01vi+T5ZlHbO0XufJ/oN0FwqsHhggLpcZ37uPZckCT8sT9zoE"
    "bROlVEc2injY28faHTtYvm4d6fQ06w8dAhHEGO4cPrwUoU3Rltaa3NQUq27epLBzJz8ZQ3T/"
    "Pii1JBHyfX2IUnQM2q+3z+5bt1hdKGDjmOj5c1pxTKvRoDU/j+7qIlizBkRQnxN8HuHt4CBv"
    "Xr1iulhEhSGLlQrZ3BwuTcnqdZJKBZdlnwja/9A2SlasYOrIEXI3rhM3m6zcsAEdhiwuLNBS"
    "ivlqFZyTDsH3ppGGIbe3bMEVfqFcqZBEEX+Nj/Pv5CQvii/xurqefmFgjOloYmKCwPoMDR/j"
    "18uXWNa/m9elEtpaNj4eY/L4MPuiqP+LCJ7nUXpTwoY+vx0YIJ/Po7UmatRZ/vsQsqqH2bt3"
    "mZ37QLX2DmDeAHieR61WJVlcYPPWTXiej3Mt5uqzgHzazG29/Lytl/fva8zMzCwZ+L5/6uq1"
    "KyO1WhURYezR2Dfr/HU55wiC4A8g/R8/Pf1dkwClZQAAAABJRU5ErkJggg==")
getExitData = Exit.GetData
getExitImage = Exit.GetImage
getExitBitmap = Exit.GetBitmap
#----------------------------------------------------------------------
News = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "B3RJTUUH2AsaAA8jXzLftQAAEKVJREFUeJztnHtsHNV+xz9nZvbheLNrJ45xbMfYeTqPC0EU"
    "rqnAlEIegosqVTzLI0CVWNCKSgjEQwVNwiviSkjoSlHQLRCUEqKoqEUEVIQUoRCJQpqQEJJY"
    "SWQKwSnESfyIs695nP7hzDC7O2vv+hVTzUca7ezZM2fOnO/8zu/Mb85ZCAgICAgICAgICAgI"
    "CAgICAgICAgICAgICAgICAgICPBDXOoKeNF1PRqJRCoudT3ysSwrbpqm6vebpmmGaZrduq7b"
    "43GuUQmi63pYVdV/klL+PdAChMejMr9h+qWU/yKlfEXX9XNjKWhUgmzYsOFd4MFyjolEIghR"
    "+umklOVWa0wIIQiHh7+v8uskhGBwcBDbdo2j07btq3VdT462Hlq5B+i6Xgf8HcADDzxAY2Mj"
    "quprzWNmOFHKEXcikVLS19fH1q1bGRgYaFUU5XFg42jLU8o+QFH+CtBaW1tpbm5G0zSEECVt"
    "5TKeZUkpJ2QDqKqq4vbbb3dOdUfZlfNQtoVIKduEECxfvhwAy7IwDGMsdfhNoygKmqbR2Njo"
    "JF31yiuvzHruued6RlXeKI65DuCyyy4D8PafvkzUnTlVNsuyANA0jebmZgDFNM0Vo2hXoExB"
    "dF2PCiGWCyGorKx0KzSSSf9/x7kply1bBoAQYuVoyypLEEVRrgTCDQ0NKIriVsYrwJtvvklN"
    "TQ2zZs1iYGDATX/jjTeYOXMm1dXVPPTQQ1x55ZVMmzbNd9u5cye1tbXMmDGDRx99tKjYt912"
    "G9XV1dTW1nLw4EFOnTrFvffey+zZs4nFYsyePZv29nY3fzKZ5Ny5c2Pa+vv7fa1ESklTUxMA"
    "UspRW0hZPkQI0SalZNGiRQCuuXpZt24dx48f58MPP2Tbtm10dHQA8Pjjj/Pjjz8yd+5cHnvs"
    "MdLpNI2NjfT09CCEQEpJNpulo6ODW2+9lS1btrB161Y2bdrklv3oo4+SyWR4++23Adi5cycd"
    "HR3cfPPNXHHFFdx9990kEgkOHjzIjBkz6O7u5qmnnqK3t5fq6mrS6TSnTp0abVsBoKoq8Xg8"
    "J82xkEQiQSQSIZPJ1G/YsOF3L7zwwqFyyy/LQqSUbYDrwPKtw9mOHDnC888/z5YtWwrSlyxZ"
    "gpSS7u5uZs+e7ZQLQDgc5p133gFg5cqVHDp0iJ6eHvf4rq4uDh06lFPm559/zi233IKUkp9+"
    "+om1a9dSU1ODoijMmTOH7du3U1VVhZSScDg8Zp9hmiaZTCYnzWkHIQRLliwBRt9tlevU2wBm"
    "zpzpCuLH0aNHWbFiBfX19Xz11Vc56YsXLwbg5MmT3pEJ69evz62YonD//ffz/vvvu2m9vb0s"
    "XbqUrq4uAI4cOUJDQwPV1dXAkIibN2/GNE3fekUikfKutgiZTKYgzWmLhQsXAiClnFhBLj4Q"
    "NodCISoqhsJNfg793LlzZLNZamtreeihh3jrrbeQUnL27FlM02TWrFlIKTl58iS7d+8mFosR"
    "i8U4depUQVkPPvgg27ZtQ0pJOp0mGo3S3t7O7t27kVLy2WefsXr1ajf/008/TSgUYvny5ei6"
    "zuHDh3PKc4aoY7WSVCpVdLTlWD1ww+uvv152XK5kQYQQ1wHMnz8fIYRrpvl4rWD16tV8+eWX"
    "9PX15aQD/PTTTzz55JOcP3+evr4+1yF6ueyyy5g/fz579+7lhx9+oKmpifb2dr744gsAdu3a"
    "xapVq9z84XCYTZs28cknnxCLxbjnnntYs2ZNzh0djUZLveSipFKpgjSnPSoqKpwepOLChQs3"
    "lFt2OYJcCzBv3jzA3zocP7F48WL3jrzjjjt47733OHz4sJvu9PeNjY1uvmeffda3vEceeYR3"
    "332Xrq4uWlpaaGlpoauri1Qqxffff8+yZcsKjmlsbOSJJ55g7969JJNJ/vSnP7m/hUKhMVtI"
    "Op0uSLNtu2D4a9t22d1WOT7kWhgySacCfuRbwpo1a9iyZQtHjx6ltbXVTT958iRz5swZ8aQ3"
    "3ngj3377Ld99953z4MW8efPYunUr7e3tOXl37drFp59+6n4Ph8OsWbOGr7/+2k0bDwvJZrO+"
    "1+90Wy0tLcDoHHtJguzYsUPloiBVVVXuyf3uHqfhne9z5syhvr6eDz74IMdCuru7aWhocL9n"
    "s1leffVVTpw4UVDmnXfeyebNm2lubkZKyQ033MBrr73GypUrc/LV1dXx8ssvs2fPHjKZDKdP"
    "n2b79u20tLS4ecZjpDWcH5FSUlNT48Tblum6Xj/ugnR2di4DYvF43A1R5z+DnDt3juuvv549"
    "e/awdu1avvnmG/e3hx9+mN7eXlpbW+np6eG6666js7OTtrY2EokEiUSCmpoa3njjDffu8nLf"
    "ffcxMDDgWkh7ezu9vb3cdNNNOfmam5tZuHAh69ato66ujquuugpVVXnmmWfcPOM10kqn0wVp"
    "jtVomsbcuXMBhBCirIfEksKmL774YoeUcvO1117LihUrsCyLZHLUIf9LTjabHXMZqqr6vnaI"
    "RCKoqsqhQ4f4+OOPAba98MIL95VabkkWIi8+EDojIb8n9N8S4XB4zFuxd0BO23j84wpd10v2"
    "1aWGTtoAamtrc/rKgEJM0yQUChGPx6moqCCVSs0ClgP7Szl+ROU2btyYABYCTJ8+HfjtW8hE"
    "4jh4IYQ72lQUpeTR1oiCZDKZawFlzpw5qKqaYyHB5r85oRvnmQ1YVax98xmxy/I+oYO/dXR2"
    "dk6q1SxevNgN/1uW5fvkPJlEo1E07demtCwLTdOoq6tzkv5S1/WYruuDI5VVig9pA6ivr3dP"
    "5vUfmUyGzs7O0ms/DixYsIBQKARAMpnkwoULk3r+fCzLygnJm6ZJJBKhoqKC2tpaTp8+HRZC"
    "3Ah8PFJZwwoipRQvvvji72Eowus1R4fe3l5334kCTwSWZdHX11eQ7gQ6LyV+dbAsC1VVaW1t"
    "5fTp0zDUbY1NkJdeemkhMCMUCjFt2jRgSH2vhTiCVFdXeyOd445XEKevhqEwfWVl5YSdt1Ty"
    "R52maaIoCpdffjlQehhlJAu5BoacU7EIryNINBqdUD9SrGwppfvC6FLhTLJz/Br8Wl/nZZlt"
    "24t0XW/Sdf3H4coaSZA2IYQbzsi3DsC9a0OhUNEXQ+OBN5jntZDBwcFL7kNgqNvy+hHLsrBt"
    "G1VVmTt3LidOnEAIsQr483DlDCuIEKINcEcL+Xfp4OAghmEghEBRlEkTxEskEvG9USYbvyiy"
    "M9pasGCBI8hKRiuIruvTgCthyD84Dt174V7rKPbCarwoZiGappFIJCbsvOXg50c0TaOhocFJ"
    "unnHjh3qXXfdVbRvLyqIpml/Ydu2VlVVVTTC6/iP4bqr8RJpuAl5hmFccguBoZsj349IKUkk"
    "EsRiMQYHB6uPHTt2DfBfRcso9oNt222Q+4Ywv1EcC9E0bUK7q4v1cfe9FjIwMMDAwMCEnrtU"
    "VFXNGWlKOfQiT1EUFi5cyP79+523iOULAlwDQ1FLv+cPKSX9/f3u94kWpJgFhMNhd+LCpcbv"
    "ecQ0TcLhMM3Nzezfvx9gJbChWBnDCeJGeJ2C8/2HE0TzE2y88Z7bayGRSMSdZzwV8PMjoVDI"
    "G0b5/caNGxPPPPNMf8HBFBFE1/VGoFFRFHcol9/gjnWoqjopcazhLGCiBxTlkP+exPEj0WiU"
    "uro6fv75Zy2Tyfw18O9+x/sKoqpqm5SS+vp6FEUZNmQyGdbhnMe77/UhZ86cmVKCNDU1FTh3"
    "VVVZsGABP//8szP8LV0QKeV1gPNe2HecP5n+Ix+vIN6w91Qhvz6GYaAoinemZtFwfDFB2oQQ"
    "br+X3+CmabpPx5Mpht/KqXg8XjD5earhDaNc7OJbdF2fr+v6ify8BYLouq4JIa5yCoDi/sN7"
    "ssnA+87ht4QziU5VVebNm8exY8ect4gjC3JxDUhFRUUFsVjMvSu9jeGM+23bnlQLceqgaZq7"
    "n0wmp5QPgaEIdG1tbcGUI0VRmDt3LseOHYOhbmtT/rEFgjhrQFpaWlyHrihKjpNyLMQwjEn3"
    "H5AriGmaIy6rm2ych+h8i3aWSFzkpjfffDPU0dGRs0CzQBB5ccpPc3OzG3LPL9h5QjcMY9Ia"
    "w2sBXkFqa2upqqqaUqIoiuK75l1RFKqrq4nH4wwMDEz/5Zdf2oAvvHn8OuU2GJp5bts2hmG4"
    "owQpJYODg6TTaaZPn048Hi8Yd09U12HbNkII+vv7C1b9CiEmbK38aPFbmexExRcsWMC+ffuQ"
    "Uq5iOEFeffXVasMw5sPQ6MW2bTKZDNFo1BWku7ubaDRKPB7HMIwR//1gvHBCEIZhkM1mXeEz"
    "mQy9vb1TcmpSRUWFu5gIhm7WUChEQ0MD+/btA7gZ+GfvMTmCGIaxEKCyshJFUdw16JFIxL1g"
    "Z+aeaZrE4/Ec3zLRZDIZwuEw6XTa9V29vb057/WnEgMDA0SjUXdg5LShM2FdCPE7XdcV7x/X"
    "5AgipZwvhGDmzJnuUG1wcDAnaJbNZslms0ybNo2zZ89OqoVUVlaSzWZJpVKuDwmHwyQSiSk1"
    "ynIIhUI5k7INw0DTNHdesGVZlUAz0OXk8QoigCoYevtlmiaGYTAwMIBt21RWVpLJZEilUmQy"
    "GZLJJIZhTPika6ehnSF2MpkknU7n+IzR/t3GRJM/Z0xVVaLRKLZtEw6HSaVSKIqSM0PDEUQA"
    "qmEYyXA4jG3bbneVSqVIpVL09Pz6TxGJRIK+vj5s2+bChQuT0n8LIdxuyivIRE2UG4vFaZrm"
    "+0o3FAqRzWaxLMu9lnzn7xVEmKb5v+FwmL6+Pjd+5XexsViMbDZLMpl05/tOJul02vVdg4OD"
    "U3JpxKxZswqsVgiBYRhcuHDBEcLs7u7+H28eryAcPnz4v6+55hrzzJkzWjKZdP2D3+KUyspK"
    "otGou96uVMajr/cu4nSGvFPJh2ia5ttm8XicbDZLd3c3AFLKfW+//XbO3eQIIgH50Ucfnb/6"
    "6qv/U1GUPxw/fpxFixbR0NDAiRMnfE8ATOooyyG/LqXWYbJEs227wHfMnDkTIQTJZJITJ4ZC"
    "WKZpbmGo7V0cQZxhl0ilUn+srKz8w4EDB6itrSUWi7Fo0SJ3/A+F7ybyKXbhpaSXc+xoj/NL"
    "H+l7Ofm8ad6VVul0ms7OTpLJJFLKM2fPnv1Xfm17oHBJmwDU9evXbxFC3BcKhVi6dClNTU3u"
    "cuJSKlJu443mt/EoY7LqbVkW/f39nDx50gnMStu2/1bX9f/IP19+6EQC5vnz5zumT58eMwzj"
    "bw4cOMDBgweJxWLuE3uxE49EqXnL7VomotzxKNN5m5pOp70jUUNK+Q9+YsAwiz6llGL9+vX3"
    "CiH+0VkjEjAmssC/2bb9R13XDxTLVNLTlK7rzUKIxVLK6ZZlKZZlKbZtCymlsG07Z19K6e4D"
    "WJblpkkpFQDnN0+6kFIKJ82pl0+6+1kKQggphJDOvvcTkM7vTpqiKLb3Uwhhe/MoiiIVRclP"
    "s73piqJIVVVtVVVtTx1Oa5r23XPPPXd2xDqXenFFjhUMLYvL3/LThedzuH2/jbz9Uuot8/Zl"
    "3n6xzfbZ937m73u/W3nnGhUTEW/wE6MUQWB0Yjjf/RpC+nyOJFC+EH6i2HnljhuTHQDyNraf"
    "ZeTnweczf9+PfAvJ/yxFkDHf7aNh6kXkCilWx2LpxRpx6jzKBwQEBAQEBAQEBAQEBAQEBAQE"
    "BAQEBAQEBAQEBAT8Fvg/PCqMPgIBzh0AAAAASUVORK5CYII=")
getNewsData = News.GetData
getNewsImage = News.GetImage
getNewsBitmap = News.GetBitmap
getNewsIcon = News.GetIcon

#----------------------------------------------------------------------
NewsSmall = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAsACwALDnu/73AAAA"
    "CXBIWXMAAAsSAAALEgHS3X78AAAAB3RJTUUH1QMLCwM0GEqSegAAAD50RVh0Q29tbWVudABD"
    "cmVhdGVkIHdpdGggVGhlIEdJTVAKCihjKSAyMDAzIEpha3ViICdqaW1tYWMnIFN0ZWluZXIn"
    "M+9YAAABHUlEQVQ4y6WTvU7DMBSFP0OeIWN2OkeKKhQByZSdVwEqUKaoqC2vwt6JKAMbqURf"
    "IWPpC9hNZIaQNM0PauEstq/v+XxsyWK2mGr+IQPg4e7xT+b5y3MJANhsNieZTdPcJ6gURREA"
    "tm2Tpmk9D4IAgOVyCVCvAc766JW5PR98g0phGP7a3Dy5F1BFbBratTbIaG9algVAlmWDpw4m"
    "6NPRCZRSnUalFL7v99YHE1TRK8Vx3AF4nldDaoBUCtd1QQOiHJRUOI4DWoMQBwk6ACUlSZJw"
    "QBAcmMuS5vrqht0u3wO+tlukVIzHY/I8BwRCaNACBBjnjZsKKHTx01cCXtfrz9vRxYiiKI78"
    "CZrV6gPgTQDMFtN34PLUzzi5f5p8A08XeSoq7ZcmAAAAAElFTkSuQmCC")
getNewsSmallData = NewsSmall.GetData
getNewsSmallImage = NewsSmall.GetImage
getNewsSmallBitmap = NewsSmall.GetBitmap
getNewsSmallIcon = NewsSmall.GetIcon

